version: 2
registries:
  composer-repository-gravity:
    type: composer-repository
    url: https://composer.gravity.io
    username: "${{secrets.GRAVITY_USERNAME}}"
    password: "${{secrets.GRAVITY_PASSWORD}}"
  composer-repository-my-yoast:
    type: composer-repository
    url: https://my.yoast.com/packages/
    username: token
    password: "${{secrets.MY_YOAST_TOKEN}}"

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: wpackagist-plugin/disable-comments
        versions:
          - "> 1.11.0"
    registries:
      - composer-repository-gravity
      - composer-repository-my-yoast
  - package-ecosystem: composer
    directory: "/html/app/themes/philco-jcf"
    schedule:
      interval: daily
      time: "23:00"
    open-pull-requests-limit: 99
    registries:
      - composer-repository-gravity
      - composer-repository-my-yoast
